/** @type {import('next').NextConfig} */
const fs = require('fs');
const path = require('path');

// Old blog slugs -> shortened slugs (generated by scripts/shorten-slugs.mjs)
const slugRedirects = fs.existsSync(path.join(__dirname, 'slug-redirects.json'))
    ? require('./slug-redirects.json')
    : [];

const nextConfig = {
    redirects() {
        return slugRedirects.map((r) => ({ ...r, permanent: true }));
    },
    images: {
        remotePatterns: [
            {
                protocol: 'https',
                hostname: 'assets.coingecko.com',
                port: '',
                pathname: '/coins/**',
            },
            {
                protocol: 'https',
                hostname: 'coin-images.coingecko.com',
                port: '',
                pathname: '/coins/**',
            },
            {
                protocol: 'https',
                hostname: 'valorisvisio.top',
                port: '',
                pathname: '/**',
            },
        ],
        formats: ['image/webp', 'image/avif'],
        minimumCacheTTL: 31536000, // 1 year
        dangerouslyAllowSVG: true,
        contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    },
    experimental: {
        optimizeCss: true,
    },
    compress: true,
    poweredByHeader: false,
    generateEtags: false,
    httpAgentOptions: {
        keepAlive: true,
    },
}

module.exports = nextConfig
